name: Diffpose
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.1
  - asttokens=2.0.8
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - blosc=1.21.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates
  - cairo=1.16.0
  - certifi=2022.9.24
  - cfitsio=3.470
  - charls=2.2.0
  - cloudpickle=2.0.0
  - cudatoolkit=11.0.221
  - cycler=0.11.0
  - cytoolz=0.11.0
  - dask-core=2022.7.0
  - decorator=5.1.1
  - easydict=1.9
  - einops=0.4.1
  - executing=1.0.0
  - expat=2.4.4
  - fftw=3.3.9
  - filterpy=1.4.5
  - fontconfig=2.13.1
  - fsspec=2022.7.1
  - giflib=5.2.1
  - glib=2.68.4
  - glib-tools=2.68.4
  - graphite2=1.3.14
  - gstreamer=1.18.5
  - h5py=3.7.0
  - harfbuzz=2.7.2
  - hdf5=1.10.6
  - icu=67.1
  - imagecodecs=2021.8.26
  - imageio=2.19.3
  - intel-openmp=2021.4.0
  - ipython=8.4.0
  - jedi=0.18.1
  - jpeg=9e
  - jxrlib=1.1
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.84.0
  - libdeflate=1.8
  - libevent=2.1.10
  - libffi=3.3
  - libglib=2.68.4
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libopencv=4.5.1
  - libpng=1.6.37
  - libpq=12.9
  - libprotobuf=3.20.1
  - libssh2=1.10.0
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxml2=2.9.10
  - libzopfli=1.0.3
  - llvmlite=0.38.0
  - locket=1.0.0
  - lz4-c=1.9.3
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - networkx=2.8.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numba=0.55.1
  - numpy=1.21.5
  - numpy-base=1.21.5
  - opencv=4.5.1
  - openjpeg=2.4.0
  - openssl=1.1.1
  - packaging=21.3
  - parso=0.8.3
  - partd=1.2.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.1.2
  - pixman=0.40.0
  - prompt-toolkit=3.0.30
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-opencv=4.5.1
  - pygments=2.13.0
  - pyparsing=3.0.9
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.7.1
  - pywavelets=1.3.0
  - pyyaml=6.0
  - qt=5.12.9
  - scikit-image=0.19.2
  - scipy=1.7.3
  - setuptools=63.4.1
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.39.2
  - stack_data=0.5.0
  - tbb=2021.5.0
  - tensorboardx=2.2
  - tifffile=2021.7.
  - timm=0.4.12
  - tk=8.6.12
  - toolz=0.11.2
  - torchvision=0.8.2
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.3.0
  - typing_extensions=4.3.0
  - wcwidth=0.2.5
  - wheel=0.37.1
  - x264=1!161.3030
  - xz=5.2.5
  - yacs=0.1.8
  - yaml=0.2.5
  - zfp=0.5.5
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - absl-py==1.2.0
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - google-auth==2.11.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - idna==3.3
    - importlib-metadata==4.12.0
    - iniconfig==1.1.1
    - joblib==1.2.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - oauthlib==3.2.0
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.1.3
    - tensorboard==2.10.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - thop==0.1.1-2209072238
    - threadpoolctl==3.1.0
    - torchaudio==0.7.2
    - urllib3==1.26.12
    - werkzeug==2.2.2
    - zipp==3.8.1
